pulse scan changes

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -51,6 +51,10 @@ before_script:
   - retry 5 20 docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN gitlab-master.nvidia.com:5005
   # Login to NGC to pull images
   - retry 5 20 docker login -u '$oauthtoken' -p $NVCR_TOKEN nvcr.io;
+  - AuthHeader=$(echo -n $SSA_CLIENT_ID:$SSA_CLIENT_SECRET | base64 -w0)
+  - >
+    export SSA_TOKEN=$(curl --request POST --header "Authorization: Basic $AuthHeader" --header "Content-Type: application/x-www-form-urlencoded" ${SSA_ISSUER_URL} | jq ".access_token" |  tr -d '"')
+  - if [ -z "$SSA_TOKEN" ]; then exit 1; else echo "SSA_TOKEN set!"; fi
 
 stages:
   - prepare
@@ -301,9 +305,10 @@ prepare:
   <<: *tags_definition
   script:
     - |
-      git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-master.nvidia.com/sectooling/scanning/contamer.git
-      cd contamer
-      pip3 install -r requirements.txt
+      # git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-master.nvidia.com/sectooling/scanning/contamer.git
+      # cd contamer
+      # pip3 install -r requirements.txt
+
       docker pull ${IMAGE_NAME}:${CUDA_VERSION}-devel-${OS}${IMAGE_TAG_SUFFIX}
 
       # CVE-2020-14352 CVE-2020-15888: librepo, lua-libs packages WAIVED via https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=3028123&cmtNo=35
@@ -315,20 +320,28 @@ prepare:
       # CVE-2021-3501  WAIVED via https://nvbugs/3303060
       # CVE-2021-27219 WAIVED via https://nvbugs/3317302
       # CVE-2021-25217 WAIVED via https://nvbugs/3321404
-      python3 contamer.py --debug-logs -ls --fail-on-non-os ${IMAGE_NAME}:${CUDA_VERSION}-devel-${OS}${IMAGE_TAG_SUFFIX} \
-          --suppress-vulns CVE-2021-27219 CVE-2020-14352 CVE-2020-15888 CVE-2019-25013 CVE-2020-8625 CVE-2021-25215 CVE-2020-12362 CVE-2020-36313 CVE-2021-3501 CVE-2021-25217 | tee /tmp/output
+      # python3 contamer.py --debug-logs -ls --fail-on-non-os ${IMAGE_NAME}:${CUDA_VERSION}-devel-${OS}${IMAGE_TAG_SUFFIX} \
+      #     --suppress-vulns CVE-2021-27219 CVE-2020-14352 CVE-2020-15888 CVE-2019-25013 CVE-2020-8625 CVE-2021-25215 CVE-2020-12362 CVE-2020-36313 CVE-2021-3501 CVE-2021-25217 | tee /tmp/output
+
+      docker save ${IMAGE_NAME}:${CUDA_VERSION}-devel-${OS}${IMAGE_TAG_SUFFIX} > ${IMAGE_ARCHIVE}
+
+      pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN scan -i $IMAGE_ARCHIVE -o
+
       retval=$?
-      echo "Contamer return value: ${retval}";
+      echo "Pulse Scan return value: ${retval}";
 
       docker rmi -f ${IMAGE_NAME}:${CUDA_VERSION}-devel-${OS}${IMAGE_TAG_SUFFIX}
       if [[ $retval -ne 0 ]]; then
           exit 1;
-      else
-          # we need to look at the output for "Traceback" because contamer doesn't return non-zero on exception failure...
-          if cat /tmp/output | grep -q "Traceback\|Exception: Image analysis failed"; then
-              exit 1;
-          fi
       fi
+  artifacts:
+    when: always
+    expire_in: 1 week
+    paths:
+      - pulse-cli.log
+      - licenses.json
+      - sbom.json
+      - vulns.json
 
 .deploy_template: &deploy_definition
   image: gitlab-master.nvidia.com:5005/cuda-installer/cuda/gitlab-cuda-builder
